@startuml deploy-accediendo-a-nodos-remotos

title **block-consumer** accediendo a nodos remotos

note as N1
Esquema de deploy para organizaciones
que no corren peers de la Blockchain.

**block-consumer** instalado localmente
accede a cualquier peer de la red.
end note

package Blockchain {
    [peer0.afip]
    [peer1.afip]
    [peer0.comarb]
    [peer1.comarb]
}

package DataCenter {
    component [block-consumer] as BlockConsumer
    database "\nRDBMS\n" as db
}

cloud internet

BlockConsumer ..> internet
BlockConsumer ..> db : jdbc\n(read/write)
internet ..> Blockchain : gRPCs\n(read)

Blockchain -[hidden]left- DataCenter

@enduml
