@startuml diagrama-de-entidad-relaciones

!define primary_key(x) <u>x</u>

hide circle
hide methods

class BC_BLOCK {
	  primary_key(block): Integer
      channel: String
	  peer: String
	  timestamp: Date
	  consuming_time: Date
	  valid_system_txs: Integer
	  invalid_system_txs: Integer
	  valid_user_txs: Integer
	  invalid_user_txs: Integer
}

class BC_VALID_TX {
	  primary_key(block): Integer
	  primary_key(txseq): Integer
	  {field} txid: String (index)
	  org_name: String
	  timestamp: Date
	  chaincode: String
	  function: String
	  excluded_write_keys: Integer
}

class BC_INVALID_TX #DarkSalmon {
      primary_key(block): Integer
	  primary_key(txseq): Integer
	  txid: String
	  org_name: String
	  timestamp: Date
	  chaincode: String
	  function: String
	  excluded_read_keys: Integer
	  excluded_write_keys: Integer
	  error: String
	  }

class BC_VALID_TX_WRITE_SET {
      primary_key(block): Integer
	  primary_key(txseq): Integer
	  primary_key(item):  Integer
	  {field} key: String (index)
	  value: String
	  big_value: CLOB
	  {field} is_delete: Char (T | null)
}

class BC_INVALID_TX_SET #DarkSalmon {
      primary_key(block): Integer
	  primary_key(txseq): Integer
	  primary_key(item):  Integer
	  {field} type: Char (R | W)
	  key: String
	  version: String
	  value: String
	  big_value: CLOB
	  {field} is_delete: Char (T | null)
}

BC_VALID_TX --[hidden]right> BC_INVALID_TX

BC_VALID_TX "0..n" --up> "1" BC_BLOCK : < has
BC_INVALID_TX "0..n" --up> "1" BC_BLOCK : < has
BC_INVALID_TX_SET "0..n" --up> "1" BC_INVALID_TX : < has
BC_VALID_TX_WRITE_SET "0..n" --up> "1" BC_VALID_TX : < has

@enduml
