@startuml deploy-accediendo-a-nodos-remotos

title HLF-Proxy accediendo a nodos remotos

package "Blockchain\npeers remotos" as remotos {
    [orderer]
    [peer0.yyy]
    [peer1.yyy]
    [peer0.zzz]
    [peer1.zzz]
    [peer0.yyy] .[hidden]up.> orderer  
    [peer0.yyy] .[hidden]right.> [peer1.yyy]  
    [peer0.zzz] .[hidden]up.> [peer0.yyy]  
    [peer0.zzz] .[hidden]right.> [peer1.zzz]  
}  

package DataCenter {
    component [HLF-Proxy] as proxy 
    component [Aplicación\npropia] as app 
} 

cloud internet

proxy ..> internet 
app .right.> proxy : REST 
internet ..> remotos : gRPCs 
DataCenter -[hidden]left- remotos

@enduml
