@startuml deploy-accediendo-a-nodos-locales

title HLF-Proxy accediendo a nodos locales y remotos

package "Blockchain\npeers remotos" as remotos {
    [orderer]
    [peer0.yyy]
    [peer1.yyy]
    [peer0.zzz]
    [peer1.zzz]
    [peer0.yyy] .[hidden]up.> orderer  
    [peer0.yyy] .[hidden]right.> [peer1.yyy]  
    [peer0.zzz] .[hidden]up.> [peer0.yyy]  
    [peer0.zzz] .[hidden]right.> [peer1.zzz]  
} 

package DataCenter {
    component [HLF-Proxy] as proxy 
    component [Aplicación Propia] as app 
    package "Blockchain\npeers propios" as locales {
    [peer0.xxx]
    [peer1.xxx]
} 
} 

cloud internet

proxy ..> locales : gRPCs 
proxy ..> internet 
app .right.> proxy : REST 
internet ..> remotos : gRPCs 
locales .. remotos : gRPCs 

DataCenter -[hidden]left- remotos

@enduml
