-------------------------------------------------------
-- create tables
--------------------------------------------------------

--------------------------------------------------------
-- BC_BLOCK
--------------------------------------------------------
CREATE TABLE HLF.BC_BLOCK
(
BLOCK              NUMBER(10)    NOT NULL,
CHANNEL            VARCHAR2(30)  NOT NULL,
PEER               VARCHAR2(100) NOT NULL,
TIMESTAMP          DATE          NOT NULL,
CONSUMING_TIME     DATE          NOT NULL,
VALID_SYSTEM_TXS   NUMBER(5),
INVALID_SYSTEM_TXS NUMBER(5),
VALID_USER_TXS     NUMBER(5),
INVALID_USER_TXS   NUMBER(5)
)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE BC_BLOCK ADD PRIMARY KEY (BLOCK)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE HLF.BC_BLOCK ADD CONSTRAINT CHECK_BLOCK_TIMESTAMP CHECK
(
TIMESTAMP < CONSUMING_TIME
);

--------------------------------------------------------
-- BC_VALID_TX
--------------------------------------------------------
CREATE TABLE HLF.BC_VALID_TX
(
BLOCK               NUMBER(10)    NOT NULL,
TXSEQ               NUMBER(5)     NOT NULL,
TXID                VARCHAR2(100),
ORG_NAME            VARCHAR2(50)  NOT NULL,
TIMESTAMP           DATE          NOT NULL,
CHAINCODE           VARCHAR2(20),
FUNCTION            VARCHAR2(50),
EXCLUDED_WRITE_KEYS NUMBER(5)
)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

ALTER TABLE HLF.BC_VALID_TX ADD PRIMARY KEY (BLOCK, TXSEQ)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

ALTER TABLE HLF.BC_VALID_TX ADD UNIQUE (TXID)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

ALTER TABLE HLF.BC_VALID_TX ADD FOREIGN KEY (BLOCK) REFERENCES HLF.BC_BLOCK;

--------------------------------------------------------
-- BC_INVALID_TX
--------------------------------------------------------
CREATE TABLE HLF.BC_INVALID_TX
(
BLOCK               NUMBER(10)    NOT NULL,
TXSEQ               NUMBER(5)     NOT NULL,
TXID                VARCHAR2(100),
ORG_NAME            VARCHAR2(50)  NOT NULL,
TIMESTAMP           DATE          NOT NULL,
CHAINCODE           VARCHAR2(20),
FUNCTION            VARCHAR2(50),
EXCLUDED_WRITE_KEYS NUMBER(5),
EXCLUDED_READ_KEYS  NUMBER(5),
ERROR               VARCHAR2(200) NOT NULL
)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE HLF.BC_INVALID_TX ADD PRIMARY KEY (BLOCK, TXSEQ)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE HLF.BC_INVALID_TX ADD UNIQUE (TXID)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE HLF.BC_INVALID_TX ADD FOREIGN KEY (BLOCK) REFERENCES HLF.BC_BLOCK;

--------------------------------------------------------
-- BC_VALID_TX_WRITE_SET
--------------------------------------------------------
CREATE TABLE HLF.BC_VALID_TX_WRITE_SET
(
BLOCK     NUMBER(10)     NOT NULL,
TXSEQ     NUMBER(5)      NOT NULL,
ITEM      NUMBER(5)      NOT NULL,
KEY       VARCHAR2(100)  NOT NULL,
VALUE     VARCHAR2(4000),
BIG_VALUE CLOB,
IS_DELETE CHAR(1)
)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 100M NEXT 100M PCTINCREASE 0);

ALTER TABLE HLF.BC_VALID_TX_WRITE_SET ADD CONSTRAINT CHECK_VALID_TX_VALUE CHECK
(
(VALUE IS NULL     AND BIG_VALUE IS NULL     AND IS_DELETE = 'T') OR
(VALUE IS NULL     AND BIG_VALUE IS NOT NULL AND IS_DELETE IS NULL) OR
(VALUE IS NOT NULL AND BIG_VALUE IS NULL     AND IS_DELETE IS NULL)
);

ALTER TABLE HLF.BC_VALID_TX_WRITE_SET ADD PRIMARY KEY (BLOCK, TXSEQ, ITEM)
USING INDEX
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

ALTER TABLE HLF.BC_VALID_TX_WRITE_SET ADD FOREIGN KEY (BLOCK, TXSEQ) REFERENCES HLF.BC_VALID_TX;

CREATE INDEX BC_KEY ON HLF.BC_VALID_TX_WRITE_SET(KEY)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

--------------------------------------------------------
-- BC_INVALID_TX_SET
--------------------------------------------------------
CREATE TABLE HLF.BC_INVALID_TX_SET
(
BLOCK     NUMBER(10)     NOT NULL,
TXSEQ     NUMBER(5)      NOT NULL,
TYPE      CHAR(1)        NOT NULL,
ITEM      NUMBER(5)      NOT NULL,
KEY       VARCHAR2(100)  NOT NULL,
VERSION   VARCHAR2(10),
VALUE     VARCHAR2(4000),
BIG_VALUE CLOB,
IS_DELETE CHAR(1)
)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);

ALTER TABLE HLF.BC_INVALID_TX_SET ADD CONSTRAINT CHECK_SET_TYPE CHECK
(
TYPE IN ('R', 'W')
);

ALTER TABLE HLF.BC_INVALID_TX_SET ADD FOREIGN KEY (BLOCK, TXSEQ) REFERENCES HLF.BC_INVALID_TX;

CREATE INDEX HLF.BC_INVALID_KEY ON HLF.BC_INVALID_TX_SET(KEY)
-- TABLESPACE DAT_B01
STORAGE(INITIAL 10M NEXT 10M PCTINCREASE 0);
