@startuml deploy-accediendo-a-nodos-remotos

title Block-Consumer accediendo a nodos remotos

note as N1
Esquema de deploy para organizaciones 
que no corren peers de la Blockchain.

BlockConsumer instalado localmente
accede a cualquier peer de la red 
para recuperar nuevos bloques.
end note

package Blockchain {
    [peer0.afip]
    [peer1.afip]
    [peer0.xxxx]
    [peer1.xxxx]
} 

package DataCenter {
    component [BlockConsumer] 
    database "Oracle o\nPostgres\n" as db 
} 

cloud internet

BlockConsumer ..> internet 
BlockConsumer ..> db : jdbc (write)
internet ..> Blockchain : gRPCs (read)

Blockchain -[hidden]left- DataCenter

@enduml
