@startuml deploy-accediendo-a-nodos-locales

title Block-Consumer accediendo a nodos locales

note as N1
Esquema de deploy para 
organizaciones que corren 
peers de la Blockchain.

Block-Consumer se conecta 
preferentemente a peers locales 
para lograr mejor performance.

Opcionalmente, para lograr 
alta disponibilidad, se conecta 
mediante internet a peers remotos.
end note

package "Blockchain\npeers remotos" as remotos {
    [peer0.yyy]
    [peer1.yyy]
    [peer0.zzz]
    [peer1.zzz]
} 

package DataCenter {
    component [Block-Consumer] as BlockConsumer 
    database "Oracle o\nPostgres\n" as db
    package "Blockchain\npeers propios" as locales {
    [peer0.xxx]
    [peer1.xxx]
} 
} 

cloud internet

BlockConsumer ..> locales : gRPCs (read)
BlockConsumer ..> internet 
BlockConsumer ..> db : jdbc (write)
internet ..> remotos : gRPCs (read)
locales .. remotos : gRPCs (read)

DataCenter -[hidden]left- remotos

@enduml
